requires 'perl' => '5.020';
requires 'Mojolicious' => '7.84';
requires 'Capture::Tiny';
requires 'IPC::System::Simple';
requires 'MetaCPAN::Pod::XHTML';
requires 'Perl::Build';
requires 'Pod::Simple::Search';
requires 'Sort::Versions';
requires 'lib::relative';
requires 'version';
